### ISSUE TITLE
n

### ISSUE THREAD

**Issue by richardhughes260** [Ortus-Solutions/CFSelenium#3]

**Comment by lmajano** [comment]
@richardhughes260 seems your content is missing?

**Comment by richardhughes260** [comment]
I failed to Read The Fine Manual first.

Thanks for the quick reply. Please delete the item.

**Comment by richardhughes260** [comment]
Luis, sorry for the short reply, was just starting training at the gym.

Thanks for all you do & the fast reply!

I also appreciate the public display of your faith!
